basic_packages:
  - alacritty
  - alsa-utils
  - ansible
  - arandr
  - base-devel
  - bat
  - bc
  - blueman
  - bluez
  - bluez-utils
  - calc
  - cifs-utils
  - discord
  - dmenu
  - dolphin
  - dunst
  - fd
  - feh
  - firefox
  - flameshot
  - git
  - gnome-keyring
  - htop
  - i3-wm
  - i3-lock
  - imagemagick
  - irssi
  - jq
  - kitty
  - lightdm
  - neofetch
  - neovim
  - network-manager-applet
  - network-manager
  - nmap
  - npm
  - nvidia-open-dkms
  - nvtop
  - obsidian
  - pandoc-cli
  - pcmanfm
  - picom
  - pipewire
  - pipewire-alsa
  - pipewire-jack
  - pipewire-pulse
  - polybar
  - pwvucontrol
  - ranger
  - rclone
  - reflector
  - ripgrep
  - rofi
  - rsync
  - rust
  - sddm
  - seahorse
  - shellcheck
  - smartmontools
  - tcpdump
  - terraform
  - tmux
  - traceroute
  - tree
  - ttf-dejavu
  - ttf-font-awesome
  - ttf-hack
  - ttf-jetbrains-mono-nerd
  - ttf-liberation
  - unzip
  - vim
  - waybar
  - wget
  - wireplumber
  - zathura
  - zsh
  - zsh-syntax-highlighting
