Section "Monitor"
    Identifier "DVI-D-0"
    Option  "RightOf" "DP-4"
    VertRefresh 60
EndSection

Section "Monitor"
    Identifier "DP-4"
    Option  "Primary" "true"
    VertRefresh 144
EndSection
