# Shell variables
# Generated by 'wal'
wallpaper='/home/rt/wallpapers/wall.png'

# Special
background='#0d0c10'
foreground='#96b7b6'
cursor='#96b7b6'

# Colors
color0='#0d0c10'
color1='#344A4F'
color2='#335B60'
color3='#386F70'
color4='#4A4A4E'
color5='#5D605D'
color6='#A56348'
color7='#96b7b6'
color8='#69807f'
color9='#344A4F'
color10='#335B60'
color11='#386F70'
color12='#4A4A4E'
color13='#5D605D'
color14='#A56348'
color15='#96b7b6'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
