[colors]
;background = ${xrdb:color0:#222}
background = #11121d
background-alt = #15161e
;foreground = ${xrdb:color7:#222}
foreground = #a9b1d6
foreground-alt = #7c88c0
; primary = #f7768e
primary = #8867c0
secondary = #e60053
alert = #bd2c40

blue = #7199EE
cyan = #38A89D
green =  #A0E8A2
orange = #d19a66
red =  #e06c75
yellow = #D4B261
purple = #A485DD
light-gray = #565c64

[bar/bar1]
monitor = ${env:MONITOR:DP-4}
width = 100%
height = 24pt
radius = 6

font-0 = JetBrains Mono Nerd Font;2
font-1 = "Font Awesome 5 Free:style=Solid:pixelsize=10;3"
font-2 = "Font Awesome 5 Free:style=Regular:pixelsize=10;3"
font-3 = "Font Awesome 5 Brands:pixelsize=10;3"
background = ${colors.background}
foreground = ${colors.foreground}
line-size = 3pt
border-size = 4pt
border-color = #00000000
padding-left = 0
padding-right = 1
module-margin = 1
separator = |
separator-foreground = ${colors.disabled}
;modules-left = xworkspaces xwindow
modules-left = i3
modules-right = network-networkmanager weather
cursor-click = pointer
cursor-scroll = ns-resize
enable-ipc = true
; tray-position = right
wm-restack = i3
; override-redirect = true

[bar/bar2]
monitor = ${env:MONITOR:DP-2}
width = 100%
height = 24pt
radius = 6

font-0 = JetBrains Mono Nerd Font;2
font-1 = "Font Awesome 5:style=Solid:pixelsize=10;3"
font-2 = "Font Awesome 5:style=Regular:pixelsize=10;3"
font-3 = "Font Awesome 5 Brands:pixelsize=10;3"
background = ${colors.background}
foreground = ${colors.foreground}
line-size = 3pt
border-size = 4pt
border-color = #00000000
padding-left = 0
padding-right = 1
module-margin = 1
separator = |
separator-foreground = ${colors.disabled}
modules-left = xworkspaces xwindow
modules-right = filesystem memory cpu wlan date eth powermenu
cursor-click = pointer
cursor-scroll = ns-resize
enable-ipc = true
; tray-position = right
wm-restack = i3
; override-redirect = true

[module/xworkspaces]
type = internal/xworkspaces
label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 1
label-occupied = %name%
label-occupied-padding = 1
label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1
label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

[module/filesystem]
type = internal/fs
interval = 25
mount-0 = /
label-mounted = %{F#F0C674}%mountpoint%%{F-} %percentage_used%%
label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

[module/pulseaudio]
type = internal/pulseaudio
format-volume-prefix = "VOL "
format-volume-prefix-foreground = ${colors.primary}
format-volume = <label-volume>
label-volume = %percentage%%
label-muted = muted
label-muted-foreground = ${colors.disabled}

[module/memory]
type = internal/memory
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.primary}
label = %percentage_used:2%%

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.primary}
label = %percentage:2%%

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected

[module/battery]
type = internal/battery
low-at = 15
battery = BAT0

[module/backlight]
type = internal/backlight
card = intel_backlight
use-actual-brightness = true

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = %local_ip%

[module/eth]
inherit = network-base
interface-type = wired
label-connected = %{F#F0C674}%ifname%%{F-} %local_ip%

[module/date]
type = internal/date
interval = 1

# custom modules

[module/powermenu]
type = custom/menu
format-spacing = 1
label-open = 
label-open-foreground = ${colors.secondary}
label-close =  cancel
label-close-foreground = ${colors.secondary}
label-separator = |
label-separator-foreground = ${colors.foreground-alt}
menu-0-0 = reboot
menu-0-0-exec = menu-open-1
menu-0-1 = power off
menu-0-1-exec = menu-open-2
menu-1-0 = cancel
menu-1-0-exec = menu-open-0
menu-1-1 = reboot
menu-1-1-exec = sudo reboot
menu-2-0 = power off
menu-2-0-exec = sudo poweroff
menu-2-1 = cancel
menu-2-1-exec = menu-open-0

[module/weather]
type = custom/script
exec = $HOME/.config/polybar/scripts/weather-plugin.sh
tail = false
interval = 960

[module/network-networkmanager]
type = custom/script
exec = $HOME/.config/polybar/scripts/network-networkmanager.sh
tail = true

[module/network-traffic]
type = custom/script
exec = $HOME/.config/polybar/scripts/network-traffic.sh
tail = true

[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = false
strip-wsnumbers = true

;ws-icon-0 = "1;1: "
;ws-icon-1 = "2;"
;ws-icon-2 = "3;"
;ws-icon-3 = "4;"
;ws-icon-4 = "5;"
;ws-icon-5 = "6;"

ws-icon-0 = "1;"
ws-icon-1 = "2;"
ws-icon-2 = "3;"
ws-icon-3 = "4;"
ws-icon-4 = "5;"
ws-icon-5 = "6;"


; Only show workspaces on the same output as the bar
;pin-workspaces = true

label-mode-padding = 2
label-mode-foreground = #000
label-mode-background = ${colors.primary}

; focused = Active workspace on focused monitor
;label-focused = %icon%
label-focused-background = ${colors.background-alt}
;label-focused-background = ${module/bspwm.label-focused-background}
label-focused-underline = ${colors.primary}
label-focused-padding = 2

; unfocused = Inactive workspace on any monitor
;ilabel-unfocused = %icon%
;label-unfocused-padding = ${module/bspwm.label-occupied-padding}

; visible = Active workspace on unfocused monitor
;label-visible = %icon%
;label-visible-background = ${self.label-focused-background}
;label-visible-underline = ${self.label-focused-underline}
;label-visible-padding = ${self.label-focused-padding}

; urgent = Workspace with urgency hint set
;label-urgent = %icon%
label-urgent-background = ${colors.alert}
label-urgent-padding = 2


[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini
